### ISSUE TITLE
Develop Use Cases 

### ISSUE THREAD

**Issue by monicacecilia** [phenopackets/operations#1]
Develop up to three distinct use cases for pilot-testing that specify a clinical or research topic, data to be extracted, involve interactions with FHIR and Phenopackets technical components, and specify the data flow and end goals. The use cases will set the scope of development for the Core FHIR IG.

**Comment by rrfreimuth** [comment]
I think we'll need to do the following:
1. Review pre-existing docs that might have captured some of these already
2. Start a separate page (wiki or other?) for each use case; tag each as either community or driver
3. Engage the Kids First team to help provide detail and context
4. (outside the scope of use case development) Start thinking more concretely about how each component of a given use case would be realized as part of an implementation and testing plan

**Comment by ShahimEssaid** [comment]
See: https://docs.google.com/document/d/1AgmH2IHkiAPoTUizuAz5E21Q-EnfVGSYRiRvWiL3cXs/edit

**Comment by ShahimEssaid** [comment]
Use case document developed and submitted. Closing for now.
