### ISSUE TITLE
Prepare Domain Analysis Document

### ISSUE THREAD

**Issue by monicacecilia** [phenopackets/operations#2]
Develop an analysis of the Phenopackets domain, including use cases driving development, data exchange and transformation recommendations to support ETL use cases, and analysis, recommendations for any additions or modifications to the Phenopackets or FHIR data models, and mappings between those models.

**Comment by rrfreimuth** [comment]
Let's link to the DAD once the page structure is created...

**Comment by ShahimEssaid** [comment]
Domain Analysis Read the Docs setup. Home page to be the outline. See: https://github.com/phenopackets/domain-analysis

**Comment by ShahimEssaid** [comment]
Domain analysis site and outline created and submitted. Closing for now.
