### ISSUE TITLE
Submit Dissemination Plan and Activities 

### ISSUE THREAD

**Issue by monicacecilia** [phenopackets/operations#3]
Develop dissemination plan to share project goals and objectives, approach, and testing results with relevant stakeholders.

**Comment by monicacecilia** [comment]
Collaborations and Operations Manual for the Phenopackets Community can be found at https://bit.ly/cp-sub-pk-com

**Comment by monicacecilia** [comment]
There is now a draft in progress [here](https://docs.google.com/document/d/1KRwmcgMbQ9RwBz_xMM0MM_WjFU91jcIgjujxURsgvPY/edit#).

**Comment by ShahimEssaid** [comment]
Completed and submitted. Closing as complete.
