### ISSUE TITLE
Read the Docs URL and GitHub license for the domain analysis content

### ISSUE THREAD

**Issue by ShahimEssaid** [phenopackets/operations#6]
The URL for Read the Docs site is independent of the GitHub repository name. We can pick what we like as long as it is available. It has the following format:

https://the-docs-name.readthedocs.io/en/version-indicator

Right now I have two configurations:
https://da.readthedocs.io/en/latest/
https://pheno-dad.readthedocs.io/en/latest/

I favor a shorter name if it doesn't have to be self descriptive.  We should pick a stable URL going forward so links from other places don't break. There might be a Read the Docs redirect configuration to point an older project URL to a newer one but I haven't found that configuration yet.

We should also pick a license.

Related to #2

**Comment by pnrobinson** [comment]
Please specify the scope of the license? If we are talking about the FHIR IG probably CC-0 is best to reduce barriers to implementation?

**Comment by lindsmith** [comment]
Re: license - [here](https://docs.google.com/document/d/1ddfCip_uVhWgmL1rqejZdfHBFlKba4OTzFfv_R7U2_Y/edit?usp=sharing) is GA4GH's latest copyright policy. We went with Apache 2.0

**Comment by rrfreimuth** [comment]
I'd suggest relating the URL to the spec name so it is more intuitive. Options:

phenopackets-da
phenopackets-analysis

I have no strong feelings about the license, and am happy to go with GA4GH's choice for consistency.  If Phenopackets has a license, that could also be a consideration.

**Comment by monicacecilia** [comment]
Apache 2.0 is permissive and CC-0 is categorized as Public Domain. BOTH allow for the public use of the software, the former requires attribution, the latter does not (CC By 4 would). Also, Apache 2.0 has some language on patent termination and indemnification provisions - (these are overall good things), which CC-0 does not have. 

I read through the GA4GH CR Policy and I think it is okay and appropriate to instantiate these docs with an Apache 2.0 license. So I guess I vote to keep things consistent with the rest of the GA4GH portfolio. 

@pnrobinson, do you have any strong opinions about this? Else, can we go ahead with Apache 2.0?

**Comment by monicacecilia** [comment]
Oh, wrt name: phenopackets-analysis 👍

**Comment by pnrobinson** [comment]
Apache 2 is fine with me.

**Comment by ShahimEssaid** [comment]
I set the published url path to "phenopackets-analysis" and updated the readme link. Added Apache 2.0 license. Not sure if we still need copyright so leaving this issue open for now.
